server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/restapi
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.hbm2ddl.auto: update
    showSql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&
  main:
    allow-bean-definition-overriding: true